heimdall:
  version: 1.0.0
  hostname: localhost
  token_length_hours: 24
server:
  port: 9103
  servlet:
    context-path: /dio-auth
  ssl:
    key-store-password: solongandthanksforallthefish
    key-alias: heimdall-service
    key-password: solongandthanksforallthefish
    key-store: heimdall-test.jks
    enabled: true  
spring:
   datasource:
     url: jdbc:h2:mem:heimdalltest
     driverClassName: org.h2.Driver
   jpa:
     database: H2
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
   jackson:
     default-property-inclusion: non_empty
   