babelfish:
  jwk-file: heimdall-admin.jwks
heimdall:
  version: 1.0.0
  hostname: localhost
  token_length_hours: 24
server:
  port: 9102
  servlet:
    context-path: /dio-register
  ssl:
    key-store-type: PKCS12
    key-store-password: solongandthanksforallthefish
    key-alias: heimdall-service
    key-password: solongandthanksforallthefish
    key-store: heimdall-admin.p12
    enabled: true  
spring:
   datasource:
     url: jdbc:h2:file:../localdb/heimdall;AUTO_SERVER=true
     driverClassName: org.h2.Driver
   security:
      oauth2:
        resourceserver:
          jwt:
            jws-algorithm: PS256
            jwk-set-uri: https://id.dev.lab.dataright.io/auth/realms/localdev/protocol/openid-connect/certs     
   jpa:
     database: H2
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
   jackson:
     default-property-inclusion: NON_EMPTY
   devtools:
     livereload:
       enabled: false

   
