heimdall:
  version: 1.0.0
  hostname: localhost
  token_length_hours: 24
server:
  port: 9101
  servlet:
    context-path: /dio-register
  ssl:
    key-store-password: solongandthanksforallthefish
    key-alias: heimdall-service
    key-password: solongandthanksforallthefish
    key-store: heimdall.jks
    enabled: true    
    
spring:
   security:
      oauth2:
        resourceserver:
          jwt:
            jws-algorithm: PS256
            jwk-set-uri: https://localhost:9103/dio-auth/jwks
   datasource:
     url: jdbc:h2:file:../localdb/heimdall;AUTO_SERVER=true
     driverClassName: org.h2.Driver
   jpa:
     database: H2
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
   jackson:
     default-property-inclusion: non_empty

   