server:
  ssl:
    key-store-type: PKCS12
    key-store-password: solongandthanksforallthefish
    key-alias: heimdall-service
    key-password: solongandthanksforallthefish
    key-store: heimdall.p12
    enabled: true    
