babelfish:
  typeManager:
    enumerations:
      packages: io.biza.heimdall.shared.enumerations, io.biza.babelfish.cdr.enumerations
    forms:
      packages: io.biza.heimdall.shared.payloads.dio
  orika:
    packageBase: io.biza.heimdall.shared.persistence.mapper
server:
  port: 9101
  servlet:
    context-path: /cdr-register
spring:
   security:
      oauth2:
        resourceserver:
          jwt:
            jws-algorithm: PS256
            jwk-set-uri: http://localhost:8103/wikkit-auth/heimdall/jwks
   datasource:
     url: jdbc:h2:file:../localdb/heimdall;AUTO_SERVER=true
     driverClassName: org.h2.Driver
   jpa:
     database: H2
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
   jackson:
     default-property-inclusion: NON_EMPTY
   devtools:
     livereload:
       enabled: false

   
