deepthought:
  version: 1.0.0
server:
  port: 8081
  servlet:
    context-path: /cdr-register
spring:
   security:
      oauth2:
         resourceserver:
            jwt:
               jwk-set-uri: https://id.dev.lab.dataright.io/auth/realms/deepthought/protocol/openid-connect/certs
   datasource:
     url: jdbc:h2:file:../localdb/basedb;AUTO_SERVER=true
     driverClassName: org.h2.Driver
   jpa:
     database: H2
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
   jackson:
     default-property-inclusion: non_empty

   