spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heimdall
    username: localdb
    password: localdb
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
